config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'reviews#index'

  
  resources :reviews do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, :artist, :text, :image, presence: true
  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader
  
  def self.search(search)
    if search
      Review.where('artist LIKE(?)', "%#{search}%")
    else
      Review.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews 
  has_many :comments 

  validates :nickname, presence: true, length: { maximum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

# deviseでは初期状態でサインアップ時にメールアドレスとパスワードのみを受け取るようにストロングパラメーターが設定してあるので、追加したキー（nickname）のパラメーターは許可されていない。

# 追加のパラメーターを許可したい場合は、application_controller.rbにおいてbefore_actionにconfigure_permitted_parametersメソッドを設定。

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to review_path(comment.review.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :move_to_index, except: [:index, :show, :search]
  
  def index
    @reviews = Review.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @review = Review.new
  end

  def create 
    @review = Review.create(review_params)
    if @review.save
      redirect_to root_path
    else
      redirect_to new_review_path
    end
  end


  def destroy
    review = Review.find(params[:id])
    review.destroy
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
    @comments = @review.comments.includes(:user).order("created_at DESC")
  end

  def search
    @reviews = Review.search(params[:keyword])
    @reviews = @reviews.page(params[:page]).order("created_at DESC").page(params[:page]).per(5)
  end
  

  private
  def review_params
    params.require(:review).permit(:title, :artist, :text, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @reviews = user.reviews.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "description", :content => "Favomusic"}/
    %title favomusic
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .title
        = link_to "Favomusic", root_path
      .user_box
        - if user_signed_in?
          .user_box__name
            = link_to current_user.nickname, user_path(current_user.id)

      .login_box
        - if user_signed_in?
          = link_to "log out", destroy_user_session_path, method: :delete
        - else
          = link_to "log in", new_user_session_path
      .post_box
        - if user_signed_in?
          .post_box__text
            = link_to "post", new_review_path
        - else
          .post_box__text
            = link_to "sign up", new_user_registration_path
      
    .main
      = yield

    .footer
      .footer__text
        COPYRIGHT Favomusic 2020

app/views/reviews/destroy.html.haml
.success_page
  .success
    %h4 削除が完了しました
  .back_box
    = link_to "Back", root_path, class: "back"

app/views/reviews/edit.html.haml
.contents_new 
  .new_box
    = form_with(model: @review, local: true) do |f|
      = f.text_field :title, placeholder: "title", class: "title_form"
      = f.text_field :artist, placeholder: "artist", class: "artist_form"
      = f.text_area :text, placeholder: "text", class: "text_form"
      .image_form
        = f.label :image, class: "image_label" do
          .image_upload image
          = f.file_field :image, placeholder: "image url", class: 'hidden'
      .btn_box
        = f.submit "SEND", class: "btn_box__btn"

app/views/reviews/index.html.haml
.search_box
  = form_with(url: search_reviews_path, local: true, method: :get, class: "search_form") do |f|
    = f.text_field :keyword, placeholder: "artist search", class: "search_input"
    = f.submit "search", class: "search_btn"
.contents
  - @reviews.each do |review|
    .content_post
      .review_title
        = review.title
      .artist_name
        = review.artist
      .image
        = link_to image_tag(src = review.image.url, size: '250x250'), review_path(review.id)
.paginate
  = paginate(@reviews)

        
      
    

app/views/reviews/new.html.haml
.contents_new 
  .new_box
    = form_with(model: @review, local: true) do |f|
      = f.text_field :title, placeholder: "title", class: "title_form"
      = f.text_field :artist, placeholder: "artist", class: "artist_form"
      = f.text_area :text, placeholder: "text", class: "text_form"
      .image_form
        .image_upload image
        = f.file_field :image, placeholder: "image url", class: 'form'
      .btn_box
        = f.submit "SEND", class: "btn_box__btn"

      

app/views/reviews/search.html.haml
.search_box
  = form_with(url: search_reviews_path, local: true, method: :get, class: "search_form") do |f|
    = f.text_field :keyword, placeholder: "artist search", class: "search_input"
    = f.submit "search", class: "search_btn"
.contents
  - @reviews.each do |review|
    .content_post
      .review_title
        = review.title
      .artist_name
        = review.artist
      .image
        = link_to image_tag(src = review.image.url, size: '250x250'), review_path(review.id)
.paginate
  = paginate(@reviews)
        
      
    

app/views/reviews/show.html.haml
.show

  .comment_field
    .comment_form
      .comment_box
        - if current_user
          = form_with(model: [@review, @comment], local: true) do |f|
            = f.text_area :text, placeholder: "Comment", rows: "2", class: "form"
            = f.submit "SEND", class: "btn"
        - else
          .strong
            %p コメントの投稿には新規登録/ログインが必要です
  .show_header
    .show_header__title
      = @review.title
    .show_header__artist
      = @review.artist



  .show_main
    .show_main__image
      = image_tag @review.image.url, size: '300x300', class: "photo"
    .show_main__text
      = @review.text
  .posted 
    Posted by
    = link_to @review.user.nickname, user_path(@review.user_id)
  
  .comment_click
    comment

  .show_under
    .comment_btn
    .comment_text
      - if @comments
        - @comments.each do |comment|
          %p
            = link_to comment.user.nickname, user_path(comment.user_id)
            = comment.text
  
 

app/views/reviews/update.html.haml
.success_page
  .success
    %h4 更新が完了しました
  .back_box
    = link_to "Back", root_path, class: "back"

app/views/users/show.html.haml
.page_title
  = @nickname
  's posted
.contents
  - @reviews.each do |review|
    .content_post
      .review_title
        = review.title
      .artist_name
        = review.artist
      .image
        = link_to image_tag(src = review.image.url, size: '250x250'), review_path(review.id)
      .under_box
        - if user_signed_in? && current_user.id == review.user_id
          = link_to "編集", edit_review_path(review.id), class: "edit"
          = link_to "削除", review_path(review.id), class: "destroy", method: :delete
.paginate
  = paginate(@reviews)